export default {
    "success": true,
    "code": 200,
    "data": [
        {
            "id": "2",
            "name": "数据中心",
            "key": "DATACENTER",
            "description": "数据中心",
            "type": 0,
            "path": "/DataCenter",
            "parentId": "0",
            "sort": 100,
            "disable": false,
            "version": 0,
            "createTime": "2020-10-26 17:49:22",
            "updateTime": "2020-10-26 17:49:23",
            "children": [],
            "authority": "DATACENTER"
        },
        {
            "id": "1",
            "name": "系统设置",
            "key": "SYSTEM",
            "description": "系统设置",
            "type": 0,
            "path": "/Setting",
            "parentId": "0",
            "sort": 0,
            "disable": false,
            "version": 0,
            "createTime": "2020-10-26 17:47:10",
            "updateTime": "2020-10-26 17:47:12",
            "children": [],
            "authority": "SYSTEM"
        },
        {
            "id": "3",
            "name": "开发者工具",
            "key": "DEVELOP",
            "description": "开发者工具",
            "type": 0,
            "path": "/DevTools",
            "parentId": "0",
            "sort": 0,
            "disable": false,
            "version": 0,
            "createTime": "2020-10-26 17:50:25",
            "updateTime": "2020-10-26 17:50:28",
            "children": [
                {
                    "id": "5",
                    "name": "代码生成器",
                    "key": "DEVELOP:GENERATOR",
                    "description": "代码生成器",
                    "type": 0,
                    "path": "/DevTools/CodeGenerator",
                    "parentId": "3",
                    "sort": 0,
                    "disable": false,
                    "version": 0,
                    "createTime": "2020-10-26 17:53:49",
                    "updateTime": "2020-10-26 17:53:52",
                    "children": [
                        {
                            "id": "27",
                            "name": "获取数据库表",
                            "key": "DEVELOP:GENERATOR:GET",
                            "description": "获取数据库表",
                            "type": 1,
                            "path": null,
                            "parentId": "5",
                            "sort": 0,
                            "disable": false,
                            "version": 0,
                            "createTime": "2020-11-06 17:08:38",
                            "updateTime": null,
                            "children": [],
                            "authority": "DEVELOP:GENERATOR:GET"
                        },
                        {
                            "id": "28",
                            "name": "生成代码",
                            "key": "DEVELOP:GENERATOR:GENERATE",
                            "description": "生成代码",
                            "type": 1,
                            "path": null,
                            "parentId": "5",
                            "sort": 0,
                            "disable": false,
                            "version": 0,
                            "createTime": "2020-11-06 17:09:27",
                            "updateTime": "2020-11-06 17:09:30",
                            "children": [],
                            "authority": "DEVELOP:GENERATOR:GENERATE"
                        }
                    ],
                    "authority": "DEVELOP:GENERATOR"
                },
                {
                    "id": "6",
                    "name": "数据监控",
                    "key": "DEVELOP:DATAMONITOR",
                    "description": "数据库信息",
                    "type": 0,
                    "path": "/DevTools/DataMonitor",
                    "parentId": "3",
                    "sort": 0,
                    "disable": false,
                    "version": 0,
                    "createTime": "2020-10-26 17:54:47",
                    "updateTime": "2020-10-26 17:54:49",
                    "children": [],
                    "authority": "DEVELOP:DATAMONITOR"
                },
                {
                    "id": "7",
                    "name": "异常信息",
                    "key": "DEVELOP:SYSTEMEXCEPTION",
                    "description": "异常信息",
                    "type": 0,
                    "path": "/DevTools/SystemException",
                    "parentId": "3",
                    "sort": 0,
                    "disable": false,
                    "version": 0,
                    "createTime": "2020-10-26 17:55:44",
                    "updateTime": "2020-10-26 17:55:47",
                    "children": [
                        {
                            "id": "8",
                            "name": "删除异常信息",
                            "key": "DEVELOP:SYSTEMEXCEPTION:DELETE",
                            "description": "删除异常信息",
                            "type": 1,
                            "path": null,
                            "parentId": "7",
                            "sort": 0,
                            "disable": false,
                            "version": 0,
                            "createTime": "2020-10-26 17:58:02",
                            "updateTime": "2020-10-26 17:58:04",
                            "children": [],
                            "authority": "DEVELOP:SYSTEMEXCEPTION:DELETE"
                        },
                        {
                            "id": "26",
                            "name": "获取异常信息",
                            "key": "DEVELOP:SYSTEMEXCEPTION:GET",
                            "description": "获取异常信息",
                            "type": 1,
                            "path": null,
                            "parentId": "7",
                            "sort": 0,
                            "disable": false,
                            "version": 0,
                            "createTime": "2020-11-06 12:12:45",
                            "updateTime": null,
                            "children": [],
                            "authority": "DEVELOP:SYSTEMEXCEPTION:GET"
                        }
                    ],
                    "authority": "DEVELOP:SYSTEMEXCEPTION"
                },
                {
                    "id": "24",
                    "name": "应用监控",
                    "key": "DEVELOP:APPLICATIONMONITOR",
                    "description": "应用健康",
                    "type": 0,
                    "path": "/DevTools/ApplicationMonitor",
                    "parentId": "3",
                    "sort": 0,
                    "disable": false,
                    "version": 0,
                    "createTime": "2020-11-05 06:26:38",
                    "updateTime": null,
                    "children": [],
                    "authority": "DEVELOP:APPLICATIONMONITOR"
                },
                {
                    "id": "25",
                    "name": "开发文档",
                    "key": "DEVELOP:DOCUMENTATION",
                    "description": "开发文档",
                    "type": 0,
                    "path": "/DevTools/Documentation",
                    "parentId": "3",
                    "sort": 0,
                    "disable": false,
                    "version": 0,
                    "createTime": "2020-11-05 07:02:57",
                    "updateTime": null,
                    "children": [],
                    "authority": "DEVELOP:DOCUMENTATION"
                }
            ],
            "authority": "DEVELOP"
        },
        {
            "id": "4",
            "name": "系统管理",
            "key": "MANAGEMENT",
            "description": "系统管理",
            "type": 0,
            "path": "/Management",
            "parentId": "0",
            "sort": 0,
            "disable": false,
            "version": 0,
            "createTime": "2020-10-26 17:51:35",
            "updateTime": "2020-10-26 17:51:37",
            "children": [
                {
                    "id": "9",
                    "name": "用户管理",
                    "key": "MANAGEMENT:SYSTEMUSER",
                    "description": "用户管理",
                    "type": 0,
                    "path": "/Management/SystemUser",
                    "parentId": "4",
                    "sort": 0,
                    "disable": false,
                    "version": 0,
                    "createTime": "2020-10-29 13:13:58",
                    "updateTime": "2020-10-29 13:14:06",
                    "children": [
                        {
                            "id": "12",
                            "name": "增加用户",
                            "key": "MANAGEMENT:SYSTEMUSER:ADD",
                            "description": "增加用户",
                            "type": 1,
                            "path": "",
                            "parentId": "9",
                            "sort": 0,
                            "disable": false,
                            "version": null,
                            "createTime": "2020-11-02 08:04:02",
                            "updateTime": null,
                            "children": [],
                            "authority": "MANAGEMENT:SYSTEMUSER:ADD"
                        },
                        {
                            "id": "13",
                            "name": "删除用户",
                            "key": "MANAGEMENT:SYSTEMUSER:DELETE",
                            "description": "删除用户",
                            "type": 1,
                            "path": "",
                            "parentId": "9",
                            "sort": 0,
                            "disable": false,
                            "version": null,
                            "createTime": "2020-11-02 08:06:47",
                            "updateTime": null,
                            "children": [],
                            "authority": "MANAGEMENT:SYSTEMUSER:DELETE"
                        },
                        {
                            "id": "14",
                            "name": "修改用户",
                            "key": "MANAGEMENT:SYSTEMUSER:MODIFY",
                            "description": "修改用户",
                            "type": 1,
                            "path": "",
                            "parentId": "9",
                            "sort": 0,
                            "disable": false,
                            "version": null,
                            "createTime": "2020-11-02 08:06:54",
                            "updateTime": null,
                            "children": [],
                            "authority": "MANAGEMENT:SYSTEMUSER:MODIFY"
                        },
                        {
                            "id": "15",
                            "name": "查找用户",
                            "key": "MANAGEMENT:SYSTEMUSER:GET",
                            "description": "查找用户",
                            "type": 1,
                            "path": "",
                            "parentId": "9",
                            "sort": 0,
                            "disable": false,
                            "version": 0,
                            "createTime": "2020-11-02 08:09:59",
                            "updateTime": null,
                            "children": [],
                            "authority": "MANAGEMENT:SYSTEMUSER:GET"
                        }
                    ],
                    "authority": "MANAGEMENT:SYSTEMUSER"
                },
                {
                    "id": "10",
                    "name": "角色管理",
                    "key": "MANAGEMENT:SYSTEMROLE",
                    "description": "角色管理",
                    "type": 0,
                    "path": "/Management/SystemRole",
                    "parentId": "4",
                    "sort": 0,
                    "disable": false,
                    "version": 0,
                    "createTime": "2020-10-29 13:15:08",
                    "updateTime": "2020-10-29 13:15:10",
                    "children": [
                        {
                            "id": "16",
                            "name": "增加角色",
                            "key": "MANAGEMENT:SYSTEMROLE:ADD",
                            "description": "增加角色",
                            "type": 1,
                            "path": "",
                            "parentId": "10",
                            "sort": 0,
                            "disable": false,
                            "version": 0,
                            "createTime": "2020-11-02 08:13:31",
                            "updateTime": null,
                            "children": [],
                            "authority": "MANAGEMENT:SYSTEMROLE:ADD"
                        },
                        {
                            "id": "17",
                            "name": "删除角色",
                            "key": "MANAGEMENT:SYSTEMROLE:DELETE",
                            "description": "删除角色",
                            "type": 1,
                            "path": "",
                            "parentId": "10",
                            "sort": 0,
                            "disable": false,
                            "version": 0,
                            "createTime": "2020-11-02 08:13:37",
                            "updateTime": null,
                            "children": [],
                            "authority": "MANAGEMENT:SYSTEMROLE:DELETE"
                        },
                        {
                            "id": "18",
                            "name": "修改角色",
                            "key": "MANAGEMENT:SYSTEMROLE:MODIFY",
                            "description": "修改角色",
                            "type": 1,
                            "path": "",
                            "parentId": "10",
                            "sort": 0,
                            "disable": false,
                            "version": 0,
                            "createTime": "2020-11-02 08:13:47",
                            "updateTime": null,
                            "children": [],
                            "authority": "MANAGEMENT:SYSTEMROLE:MODIFY"
                        },
                        {
                            "id": "19",
                            "name": "查找角色",
                            "key": "MANAGEMENT:SYSTEMROLE:GET",
                            "description": "查找角色",
                            "type": 1,
                            "path": "",
                            "parentId": "10",
                            "sort": 0,
                            "disable": false,
                            "version": 0,
                            "createTime": "2020-11-02 08:14:11",
                            "updateTime": null,
                            "children": [],
                            "authority": "MANAGEMENT:SYSTEMROLE:GET"
                        }
                    ],
                    "authority": "MANAGEMENT:SYSTEMROLE"
                },
                {
                    "id": "11",
                    "name": "权限管理",
                    "key": "MANAGEMENT:SYSTEMAUTHORITY",
                    "description": "权限管理",
                    "type": 0,
                    "path": "/Management/SystemAuthority",
                    "parentId": "4",
                    "sort": 0,
                    "disable": false,
                    "version": 0,
                    "createTime": "2020-10-29 13:16:05",
                    "updateTime": "2020-10-29 13:16:07",
                    "children": [
                        {
                            "id": "20",
                            "name": "增加权限",
                            "key": "MANAGEMENT:SYSTEMAUTHORITY:ADD",
                            "description": "增加权限",
                            "type": 1,
                            "path": "",
                            "parentId": "11",
                            "sort": 0,
                            "disable": false,
                            "version": 0,
                            "createTime": "2020-11-02 08:16:07",
                            "updateTime": null,
                            "children": [],
                            "authority": "MANAGEMENT:SYSTEMAUTHORITY:ADD"
                        },
                        {
                            "id": "21",
                            "name": "删除权限",
                            "key": "MANAGEMENT:SYSTEMAUTHORITY:DELETE",
                            "description": "删除权限",
                            "type": 1,
                            "path": "",
                            "parentId": "11",
                            "sort": 0,
                            "disable": false,
                            "version": 0,
                            "createTime": "2020-11-02 08:16:19",
                            "updateTime": null,
                            "children": [],
                            "authority": "MANAGEMENT:SYSTEMAUTHORITY:DELETE"
                        },
                        {
                            "id": "22",
                            "name": "修改权限",
                            "key": "MANAGEMENT:SYSTEMAUTHORITY:MODIFY",
                            "description": "修改权限",
                            "type": 1,
                            "path": "",
                            "parentId": "11",
                            "sort": 0,
                            "disable": false,
                            "version": 0,
                            "createTime": "2020-11-02 08:16:27",
                            "updateTime": null,
                            "children": [],
                            "authority": "MANAGEMENT:SYSTEMAUTHORITY:MODIFY"
                        },
                        {
                            "id": "23",
                            "name": "查找权限",
                            "key": "MANAGEMENT:SYSTEMAUTHORITY:GET",
                            "description": "查找权限",
                            "type": 1,
                            "path": "",
                            "parentId": "11",
                            "sort": 0,
                            "disable": false,
                            "version": 0,
                            "createTime": "2020-11-02 08:16:35",
                            "updateTime": null,
                            "children": [],
                            "authority": "MANAGEMENT:SYSTEMAUTHORITY:GET"
                        }
                    ],
                    "authority": "MANAGEMENT:SYSTEMAUTHORITY"
                }
            ],
            "authority": "MANAGEMENT"
        }
    ]
}